# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f76c2f3467e1f013f7026cae30bba665291d3ccd179a684f1a08a34d3deb15563c98ac19f9c8b3767fc0a6f651fa7890da180a0a0fe167ae1637a8722c5ac9

test:
  secret_key_base: dc518a924095cb251739848fed0c7eefccd943051a73f8000c8bef41b54f54db9331aedd8af48a9b4e82776d92746184a0797c53374ed7b2fadfd3d4473c4014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
